[package]
name = "xtask"
version = "0.1.0"
authors = ["Nathan Fisher <jeang3nie@hitchhiker-linux.org>"]
edition = "2021"

[dependencies]
clap = "4.0"
clap_complete = "4.0"
clap_mangen = "0.2"
resvg = "0.22"
usvg = "0.22"
tiny-skia = "0.6"

